config/routes.rb
Rails.application.routes.draw do
  get 'tips/content'

  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :universes, only: [:index, :show]

  get 'sign_up' => "pages#guest_sign_up"
  post 'sign_up' => "pages#create_sign_up"

  resources :stories, only: [:show] do
    resources :solutions, only: [:index, :new, :create]
  end

  mount Attachinary::Engine => "/attachinary"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :story
  acts_as_list scope: :story
  has_attachment :photo

  has_attachment :voice
end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :story
  belongs_to :user

  has_attachment :photo
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :universe
  acts_as_list scope: :universe

  has_many :pages, -> { order(position: :asc) }
  has_many :solutions
  has_many :tips

  has_attachment :photo
end

app/models/tip.rb
class Tip < ApplicationRecord
  belongs_to :story
end

app/models/universe.rb
class Universe < ApplicationRecord
  has_many :stories, -> { order(position: :asc) }
  has_attachment :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :solutions 

  def move_to(user)
    todos.update_all(user_id: user.id)
  end

  def completed?(universe)
    story_ids = universe.stories.pluck(:id)
    finished_ids = self.solutions.pluck(:story_id)

    (story_ids - finished_ids).empty?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  # before_action :authenticate_user!
  # end
  protect_from_forgery
  before_action :authenticate_user!
  helper_method :current_user

  def current_user
    super || guest_user
  end

  private

  def guest_user
    User.find(session[:guest_user_id].nil? ? session[:guest_user_id] = create_guest_user.id : session[:guest_user_id])
  end

  def create_guest_user
    user = User.new { |user| user.guest = true }
    user.email = "guest_#{Time.now.to_i}#{rand(99)}@example.com"
    user.save(:validate => false)
    sign_in(:user, user)
    user
  end


  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    reset_session
    root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :guest_sign_up, :create_sign_up]

  def home
  end

  def guest_sign_up
  end

  def create_sign_up
    current_user.update(user_params)
    current_user.guest = false
    current_user.save
    sign_in(:user, current_user)
    redirect_to story_solutions_path(session[:story_id])
  end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      current_user.move_to(@user) if current_user && current_user.guest?
      sign_up("user", @user)
      redirect_to user_root_path
    else
      render :new
    end
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:new, :create, :index]

  before_action :set_story, only: [:index, :new, :create]

  def index
    @solution = current_user.solutions.where(story: @story).order(created_at: :desc).first
    @user = current_user
  end

  def new
    @solution = Solution.new
  end

  def create
    # update user infos from solution_params[:users]
    solution = params[:solution]
    users = solution[:users]
    @user = current_user.update(name: users[:name], age: users[:age])
    @solution = current_user.solutions.new(solution_params)
    @solution.story = @story
    @solution.save
    # redirect_to story_solutions_path(@story)
    if current_user.guest
      redirect_to sign_up_path
      session[:story_id] = @story.id
    else
      redirect_to story_solutions_path(@story)
    end

  end

private

  def set_story
    @story = Story.find(params[:story_id])
  end

  def solution_params
    params.require(:solution).permit(:photo, user_attributes: [:name, :age])
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def show
    @story = Story.find(params[:id])
    @universe = @story.universe

    if params[:page]
      @page = @story.pages.find_by_position(params[:page])
    else
      @page = @story.pages.first
    end

    if params[:tip]
      @tip = @story.pages.find_by_position(params[:tip])
    else
      @tip = @story.tips.first
    end
    raise ActiveRecord::RecordNotFound unless @page
    @prev_page = @page.higher_item
    @next_page = @page.lower_item
  end

end

app/controllers/universes_controller.rb
class UniversesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @universes = Universe.all
  end

  def show
    @universe = Universe.find(params[:id])
    @stories = @universe.stories
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>dipongo</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>

    <%= render 'shared/flashes' %>

    <%= yield %>
    

    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </body>

</html>

app/views/pages/guest_sign_up.html.erb
<div class="container-log">
  <div class="content-log-sign">
    <div class="form-log-sign">
      <h3>Enregistre toi pour continuer l'aventure</h3>
      <%= simple_form_for :user, url: sign_up_path do |f| %>
        <%= f.input :first_name, label: 'Prénom', required: true  %>
        <%= f.input :last_name, label: 'Nom', required: true  %>
        <%= f.input :email,required: true, autofocus: true  %>
        <%= f.input :password, label: 'Mot de passe',  required: true  %>
        <%= f.button :submit, "Enregistrer", class: "btn btn-success text-center" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
  <div class="wide-container-home">
     <div class="renard-home-avatar">
      <%= image_tag "http://res.cloudinary.com/dipongo/image/upload/v1508577500/Composants/renard-ballons.png"%>
      </div>
      <div class="speaker"></div>
        <audio id="player">
        <source src="http://res.cloudinary.com/dipongo/video/upload/q_100/v1506349712/Composants/Dipongo.m4a" type="audio/mp3"/>
        </audio>
      <div class="images-home">

      <div class="button-univers">
        <%= link_to image_tag('http://res.cloudinary.com/dipongo/image/upload/v1506335420/Composants/cparti-bouton-orange.png') , universes_path, :id => " button-univers-container" %>
      </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "dipongo_logo.png" %>
  <% end %>

  <!-- Right Navigation -->


  <!-- Dropdown list appearing on mobile only -->

</div>

app/views/solutions/index.html.erb
<div class="wide-container-solution">
  <div class="solution-content">
    <div class="solution-title">
      <p class="text-center solution-font">Ta jolie solution!</p>
    </div>
    <div class="photo-solution text-center">
      <% if @solution&.photo? %>
        <div class="solution-user-picture text-center">
          <%= cl_image_tag @solution.photo.path, width: 300, height: 300%>
        </div>
      <% end %>
    </div>
    <div class="solution-btn text-center">
      <%= link_to image_tag("http://res.cloudinary.com/dipongo/image/upload/v1508582599/Composants/bouton-nouvelle-histoire.png"), universe_path(@story.universe)%>
    </div>
    <p class="text-center solution-font">Toutes vos jolies idées...</p>
  </div>
    <div class="row">
      <% @story.solutions.reject { |solution| solution == @solution }.each do |solution| %>
        <div class="col-xs-4 text-center solution-pics">
          <% if solution.photo %>
            <%= cl_image_tag solution.photo.path, width: 250, height: 250, data: { toggle: "modal", target: "#modalImage-#{solution.id}" } %>
          <% end %>
          <!-- The Modal Image -->
          <div id="modalImage-<%= solution.id %>" class="modal fade">
            <button type="button" class="close" data-dismiss="modal">
              <span aria-hidden="true">&times;</span>
            </button>
            <%= cl_image_tag solution.photo&.path, width: 500  %>
            <div class="desc"><%= solution.user.name.capitalize %> <%= solution.user.age %> ans</div>
          </div>
        </div>
      <% end %>
    </div>

  <!-- Modal Felic-->
  <div id="modalFelic" class="modal fade" role="dialog">
    <button type="button" class="close" data-dismiss="modal">
      <span aria-hidden="true">&times;</span>
    </button>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <p class="text-title text-center">Bravo! <%= @user.name.capitalize %></p>
          <p class="text-thinks text-center">Merci pour ta jolie solution !</p>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/solutions/new.html.erb
<div class="wide-container">
  <div class="text-center">
    <div class="slogan-text">
      <h1>Comment peux-tu aider Dipongo</h1>
      <p>Prend une photo en appuyant sur l'icon ci-dessous</p>
    </div>

    <%= simple_form_for [@story, @solution] do |s| %>

      <label class="text-center label-upload">
        <span id="upload" class="fa fa-camera span-upload"></span>
          <%= s.input :photo, as: :attachinary, label: false, input_html: {capture: true, accept: "image/*", id: "upload", class: "hidden"} %>
      </label>
      <br>
        <div class="content-user-form">
          <%= s.simple_fields_for :user, @user do |user| %>
            <div class="user-form text-left">
              <%= user.input :name, placeholder: 'prenom' %>
            </div>
            <div class="user-form text-left">
              <%= user.input :age, as: :integer, placeholder: 'age' %>
            </div>
          <% end %>
        </div>
      <%= s.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>

  <div class="renard-home-avatar">
    <%= image_tag("renard.png") %>
  </div>


</div>

app/views/stories/show.html.erb
<div class="wide-container-page-<%= @universe.name.downcase %>">
  <div class="story-div">
    <div class="story-image">
      <%= cl_image_tag @page.photo.path, width: 512, crop: :fill %>
    </div>
    <div class="story-text text-center scroll">
      <%= @page.content %>
      <% if @page.voice %>
        <div class="text-center">
          <div class="page-sound">
            <a class="page-sound-play" href="#"></a>
            <audio>
              <source src="<%= cl_video_path @page.voice.path %>" type="audio/mp3">
            </audio>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="pagination">
    <% if @next_page && @prev_page %>
      <%= link_to "", story_path(@story, { page: @prev_page.position }),class: "btn-switch arrow-left"%>
      <div class="pongo-animation">
        <%= cl_image_tag "http://res.cloudinary.com/dipongo/image/upload/c_scale,w_776/v1507200272/Composants/Pongo2-assis.png", width: 100, data: { toggle: "modal", target: "#tip-Modal" } %>
      </div>
      <%= link_to "", story_path(@story, { page: @next_page.position }), class: "btn-switch arrow-right" %>

    <% elsif @next_page %>
      <!-- <p class="space-p"></p>
      <p class="space-p"></p> -->
      <%= link_to "", story_path(@story, { page: @next_page.position }), class: "btn-switch arrow-right" %>

    <% else # last page %>
      <%= link_to "", story_path(@story, { page: @prev_page.position }),class: "btn-switch arrow-left"%>

      <%= simple_form_for [@story, Solution.new] do |s| %>
        <%= s.input :photo, as: :attachinary, input_html: {capture: true, accept: "image/*" }%>
        <div class="modal" id="solution-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-="false">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-body">
                  <h4 class="modal-title text-center" id="myModalLabel">Merci pour ta jolie solution !</h4>
                <div id="solution-preview" class="text-center"></div>
                <div class="content-user-form">
                  <%= s.simple_fields_for :users, current_user do |user| %>
                    <div class="user-form text-left">
                      <%= user.input :name, placeholder: 'Emma' %>
                    </div>
                    <div class="user-form text-left">
                      <%= user.input :age, as: :integer, placeholder: '5' %>
                    </div>
                  <% end %>
                </div>
                <div class="solution-modal-btn text-center">
                  <%= s.button :submit,'Découvre d\'autres solutions', class: "btn btn-success text-center" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <p class="space-p"> </p>
    <% end %>
  </div>

<!-- modal -->

  <div class="modal" id="tip-Modal" tabindex="-1" role="dialog" aria-labelledby="tipsModal" data-="false">
    <button type="button" class="close" data-dismiss="modal">
    <span aria-hidden="true">&times;</span></button>
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-body">
          <h4 class="modal-title" id="tipsModal">Les Conseils de Pongo</h4>
          <div class="modal-text-tips">
            <p ><%= @tip.content %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/universes/index.html.erb
<div class="wide-container-universes">
  <div class="title-univers-index">
    <h1>Où allons-nous ?</h1>
  </div>
  <section class="awSlider">
    <div  class="carousel slide">
      <!-- Indicators -->


      <!-- Wrapper for slides -->

      <div class="carousel-inner" role="listbox">
        <% @universes.each_with_index do |universe, i| %>
          <div class="item <%= 'active' if i == 0 %> ">
            <%= link_to universe_path(universe) do %>
              <%= cl_image_tag universe.photo.path %>
              <div class="univers-carousel-name">
                <p><%= universe.nickname %></p>
              </div>
              <div class="medaille">
                <% if current_user.completed?(universe) %>
                  <%= cl_image_tag("Composants/medailles.png", :width=>200, :crop=>"scale") %>
                <% else %>
                  <%= cl_image_tag("Composants/medailles.png", :width=>200, :crop=>"scale", :effect=>"grayscale")%>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>


      <!-- Controls -->
      <!-- <a class="left carousel-control" href=".carousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      </a> -->
      <a class="left carousel-control" href=".carousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true" style="font-size: 60px"></span>
      </a>
      <a class="right carousel-control" href=".carousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true" style="font-size: 60px"></span>
      </a>
    </div>
  </section>
  <div class="dropdown">
      <%= cl_image_tag("Universes/jungle/etoile-orange.png", :width=>50, :crop=>"scale", :effect=>"grayscale", class:"avatar dropdown-toggle", data: {toggle: "dropdown"})%>
    <ul class="dropdown-menu dropdown-menu-right">
      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
    </ul>
  </div>
</div>

app/views/universes/show.html.erb
<div class="wide-container-story-<%= @universe.name.downcase %>">
  <% @stories.each_with_index do |story, i| %>
    <div class="story<%= i + 1 %>">
      <% if current_user.solutions.exists?(story_id: story) %>
        <div class="star-valid">
          <%= cl_image_tag("Universes/jungle/etoile-orange.png", :width=>120, :crop=>"scale") %>
        </div>
        <div class="picture-valid">
          <%= cl_image_tag("Universes/#{@universe.name.downcase}/histoire#{i + 1}-valid.png", :width=>300, :crop=>"scale") %>
        </div>
      <% else %>
        <%= link_to story_path(story) do %>
          <%= cl_image_tag("Universes/#{@universe.name.downcase}/histoire#{i + 1}.png", :width=>300, :crop=>"scale") %>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <div class="btn-back">

    <%= link_to cl_image_tag("Composants/bouton-croix.png", :width=>100, :crop=>"scale"), universes_path %>
  </div>
</div>